name: michaelwsherer
favicon: null
layout_spectrum: 0.8867350684013218
typography_spectrum: 0.4877890709321946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#aa1e14'
    - '#91c7ff'
    - '#727272'
  brandStrength: 0.409338450524956
  lightness: 0.8646780063863844
  saturation: 0.22537441365420818
  rhythmicContrast: 0.46939466218464077
purpose: []
